# ----------------------------
# Makefile Options
# ----------------------------

NAME = HELLO
ICON = icon.png
DESCRIPTION = "Simply prints HelloWorld"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
