# ----------------------------
# Makefile Options
# ----------------------------

NAME = WAIT
DESCRIPTION = "Waits for a key to be pressed, then exits"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
